# Generated by Django 6.0.1 on 2026-04-17 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_min_length', models.PositiveSmallIntegerField(default=8)),
                ('password_require_uppercase', models.BooleanField(default=True)),
                ('password_require_lowercase', models.BooleanField(default=True)),
                ('password_require_numbers', models.BooleanField(default=True)),
                ('password_require_special', models.BooleanField(default=False)),
                ('password_expiry_days', models.PositiveIntegerField(default=90)),
                ('max_login_attempts', models.PositiveSmallIntegerField(default=5)),
                ('lockout_duration', models.PositiveIntegerField(default=15)),
                ('ip_whitelist', models.JSONField(blank=True, default=list)),
                ('ip_blacklist', models.JSONField(blank=True, default=list)),
                ('alert_on_failed_login', models.BooleanField(default=True)),
                ('alert_on_suspicious_activity', models.BooleanField(default=True)),
                ('alert_on_password_change', models.BooleanField(default=False)),
                ('alert_email', models.EmailField(blank=True, default='', max_length=254)),
                ('audit_enabled', models.BooleanField(default=True)),
                ('audit_retention_days', models.PositiveIntegerField(default=365)),
                ('log_sensitive_actions', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
