# Generated by Django 6.0.1 on 2026-06-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_profile_image'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user'], name='password_token_user_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='password_token_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='user_role_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['locked_until'], name='user_locked_until_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['user', '-timestamp'], name='userlog_user_time_idx'),
        ),
    ]
