# Generated by Django 6.0.1 on 2026-04-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyimage_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
