# Generated by Django 6.0.1 on 2026-06-05 11:45

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_options_property_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=properties.models.property_image_upload_to),
        ),
    ]
