# Generated by Django 6.0.1 on 2026-06-05 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_propertyimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', '-created_at'], name='property_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_approved', 'is_rejected', 'is_available', '-created_at'], name='property_public_list_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'uploaded_at'], name='property_image_order_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['bachelor', '-created_at'], name='wishlist_bachelor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['property', '-created_at'], name='wishlist_property_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('total_seats__gte', 1)), name='property_total_seats_positive'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('occupied_seats__gte', 0), ('occupied_seats__lte', models.F('total_seats'))), name='property_occupied_within_total'),
        ),
    ]
