# Generated by Django 6.0.1 on 2026-04-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rentrequest_options_alter_rentrequest_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitBooking',
        ),
    ]
