# Generated by Django 6.0.1 on 2026-06-05 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_propertyimage_options_and_more'),
        ('rentals', '0003_delete_visitbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rentrequest',
            index=models.Index(fields=['bachelor', 'status', '-created_at'], name='rent_req_bachelor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentrequest',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='rent_req_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentrequest',
            index=models.Index(fields=['property', 'status'], name='rent_req_property_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('bachelor', 'property'), name='unique_active_rent_request'),
        ),
    ]
